# Generated by Django 3.2.5 on 2021-09-17 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lessonview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonview',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson'),
        ),
    ]
